travis:
  secure:
    BINSTAR_TOKEN: S8kemvr/5B4nHe83BuuCoGmlZAEyZb3xENDCICR3eRAlIAIWW7BkYvUti3D1WLed6jqopDthmqM+b08OFDXKEOEXnsbZwFEws8TYvQvDoKtx4sZKReEBG8+Q+C2/Dfq7wSIej4EIS6kN1qrVcNo1nqL9M83FEbmBTvbRpwiwhjzoWMq6WxL3KMdDxTwpbuiXu5XHn9t3tatrfkfJZQ8k/AFTVwPwkMiP7pORJnfUDIeD2qOewXzYEDN6e+F0avb3ucqwjUKI/5I3wpXg7GDy+Z/nrn4kLHINJa2QdNkMRbhG9U+vnvoTfbcTyiUORyb0qLx3+XVHsm54oHQl0L/ywfKZ1Jc3SIbQLckrG4284cQ5f6DXvChurTFR6U0d8m/wLE419iw68Ep8jgiIfiFVNY7AEr/Ze9Hu0vv+YQ1FatqucsHw3Nu2fF0K1Rc2DsBWWoXzFfoeRFf1m8O/1Kwdrdf+FUF3/4WzI65CQ8/Nz3LwNqX63XsxZQPtXRuxTdbH8WrzBBb0sjyX4ETJGVepPWoCCLlV35JET2psa2bxOcwkHfY56E/fGG7+dIWmfm5sruMN64RQBKWe3uljlEHL2PlVvFAqtQg1iVPvgNPPEVa2b7dyldvr9n1ciMETjYao64owrqn4dQylsF0k9BkXSTn+aFYijttyNOZ8nfN3qVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
